nickjj/flask-static-digest0

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,44 +1,75 @@
-name: luma.emulator
+name: "CI"
 
 on:
-  push:
-    branches: [ master ]
   pull_request:
-    branches: [ master ]
+    branches:
+      - "*"
+  push:
+    branches:
+      - "main"
+      - "master"
 
 jobs:
-  build:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-        python-minor-version: [6, 7, 8, 9]
-    name: Python 3.${{ matrix.python-minor-version }}
+  test:
+    runs-on: "ubuntu-latest"
+
     steps:
-      - uses: actions/checkout@v2
-      - name: Setup pip cache
-        uses: actions/cache@v4
-        id: pipcache
+      - uses: "actions/checkout@v2"
+
+      - name: "Set up Python 3.8"
+        uses: "actions/setup-python@v1"
         with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.${{ matrix.python-minor-version }}
-      - name: Install system dependencies
-        run: sudo apt-get install graphviz libsdl-dev python3-dev python3-numpy libsdl-image1.2-dev
-      - name: Display Python version
-        run: python -c "import sys; print(sys.version)"
-      - name: Install Python packages
-        run: pip install --upgrade setuptools pip wheel tox coveralls
-      - name: Run tests
-        env:
-          TOX_ENV: py3${{ matrix.python-minor-version }}
-        run: python -m tox -e $TOX_ENV
-      - name: QA
-        env:
-          TOX_ENV: qa,doc
-        run: python -m tox -e $TOX_ENV
+          python-version: "3.9"
+
+      - name: "Install dependencies"
+        run: |
+          pip3 install flake8 Flask==1.1.2
+          pip3 install -e .
+
+      - name: "Lint code base"
+        run: |
+          flake8 .
+
+      - name: "Run test suite"
+        run: |
+          cd tests/example_app
+          export FLASK_APP=example.app
+
+          ls -laR example/static/ | wc -l
+          | grep -q "26"
+          && (echo "File count before compiling test: pass" && exit 0)
+          || (echo "File count before compiling test: fail" && exit 1)
+
+          flask digest compile
+          && ls -laR example/static/ | wc -l
+          | grep -q "36"
+          && (echo "File count after compiling test: pass" && exit 0)
+          || (echo "File count after compiling test: fail" && exit 1)
+
+          grep -q "js/modules/hello.js" example/static/cache_manifest.json
+          && (echo "Cache manifest has nested file test: pass" && exit 0)
+          || (echo "Cache manifest has nested file test: fail" && exit 1)
+
+          grep -q "js/modules/hello-d41d8cd98f00b204e9800998ecf8427e.js" example/static/cache_manifest.json
+          && (echo "Cache manifest has digested file test: pass" && exit 0)
+          || (echo "Cache manifest has digested file test: fail" && exit 1)
+
+          flask run &
+          sleep 5
+          && curl http://localhost:5000
+          | grep -q 'https://cdn.example.com/static/css/app-d41d8cd98f00b204e9800998ecf8427e.css'
+          && (echo 'Stylesheet is md5 tagged test: pass' && exit 0)
+          || (echo 'Stylesheet is md5 tagged test: fail' && exit 1)
+
+          flask digest clean
+          && ls -laR example/static/ | wc -l
+          | grep -q "26"
+          && (echo "File count after cleaning test: pass" && exit 0)
+          || (echo "File count after cleaning test: fail" && exit 1)
+
+          flask run -p 5001 &
+          sleep 5
+          && curl http://localhost:5001
+          | grep -q 'https://cdn.example.com/static/js/app.js'
+          && (echo 'Javascript is not md5 tagged test: pass' && exit 0)
+          || (echo 'Javascript is not md5 tagged test: fail' && exit 1)
